services:
  local-file-host:
    image: zeitlabs-local-file-host:latest
    build: .
    ports:
      - "${LOCAL_FILE_HOST_PORT:-8888}:8888"
    volumes:
      - ./certs:/certs:cached
      - ./assets:/assets:cached
      - ./scripts:/scripts:cached
    environment:
      HOST_USER: "${HOST_USER:-1000}"
      HOST_GROUP: "${HOST_GROUP:-1000}"
    restart: unless-stopped
